### ISSUE TITLE
Not working very well with some files

### ISSUE THREAD

**Issue by mbbill** [iskwmsy/svg2step#2]
![pawpatrol](https://github.com/iskwmsy/svg2step/assets/841602/322228f3-99dc-45a4-b416-b19bbdb54d16)

generates 

![image](https://github.com/iskwmsy/svg2step/assets/841602/9180da8d-b348-48ef-bb4c-eadab097f600)

**Comment by iskwmsy** [comment]
Hi, thank you for youe comment.

I imported your path and this is my result.
<img width="1151" alt="スクリーンショット 2024-01-17 16 59 25" src="https://github.com/iskwmsy/svg2step/assets/58510604/60a1e3ec-fc70-4e27-8389-c27a9fedd98a">
<img width="1053" alt="スクリーンショット 2024-01-17 17 02 21" src="https://github.com/iskwmsy/svg2step/assets/58510604/db19be9c-d82d-458c-8d06-b2d2452561dc">

Maybe you have imported the svg twice in the app which caused this double effect.
This is the original svg path shown in adobe illustrator.

<img width="702" alt="スクリーンショット 2024-01-17 17 01 52" src="https://github.com/iskwmsy/svg2step/assets/58510604/d832595b-55df-42c0-b42f-7dc3a4da8d18">

**Comment by mbbill** [comment]
I found the issue. I've reused the same tab (https://dev.cog.ooo/svg2step/) to convert several slightly different svgs and it somehow can't output correctly. I killed that tab and the new one works as expected.
